version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.10
    steps:
    - checkout
    - run: yarn install
    - run: yarn build
  test:
    docker:
    - image: circleci/node:8.10
    steps:
    - checkout
    - run: yarn install
    - run: yarn test
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
          requires:
            - build